global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
runtime:
  gogc: 75

scrape_configs:
  - job_name: prometheus
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090
  - job_name: exemplo
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets:
          - <IP>:3000
otlp:
  translation_strategy: UnderscoreEscapingWithSuffixes